Repository hmcts/pcs-api, pull requests merged in 2024-12, with the labels that each got.

#26 Hdpi 93 a
  .gitignore
  Jenkinsfile_CNP
  build.gradle
  src/e2eTest/.yarnrc.yml
  src/e2eTest/config.ts
  src/e2eTest/package.json
  src/e2eTest/playwright.config.ts
  src/e2eTest/tests/placeholder.spec.ts
  src/e2eTest/yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-26

#29 HDPI-95 - Adding run changed tests helper
  src/e2eTest/helpers/runChangedTestHelper.ts
  src/e2eTest/package.json
  src/e2eTest/tsconfig.json
  src/e2eTest/yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-29

#30 HDPI-98 - Adding Nightly E2E test runs
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  src/e2eTest/package.json
  src/e2eTest/tests/placeholder.spec.ts
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-30

#31 HDPI-100 - Updating README.md for E2E testing
  README.md
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-31

#33 Disabling E2E tests due to S2S auth being required
  Jenkinsfile_CNP
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-33

#28 Add s2s auth to api
  Jenkinsfile_CNP
  build.gradle
  charts/pcs-api/Chart.yaml
  charts/pcs-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/pcs/controllers/SampleFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcs/controllers/GetWelcomeTest.java
  src/main/java/uk/gov/hmcts/reform/pcs/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pcs/config/ServiceTokenGeneratorConfiguration.java
  src/main/resources/application.yaml
  src/smokeTest/java/uk/gov/hmcts/reform/pcs/controllers/SampleSmokeTest.java
Labels: aat/no-changes, ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-api-pr-28
