Repository hmcts/pcs-api, pull requests merged in 2025-10, with the labels that each got.

#620 HDPI-1657-Introductory, demoted or other tenancy
  src/e2eTest/data/page-data/groundsForPossession.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/IntroductoryDemotedOrOtherGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/IntroductoryDemotedOrOtherNoGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/IntroductoryDemotedOtherGroundReason.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleGroundsReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/ClaimEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/ClaimGroundEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/GroundForPossessionAdditionalGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/GroundsForPossession.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/IntroductoryDemotedOrOtherGroundsForPossession.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/IntroductoryDemotedOtherGroundsReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/RentArrearsOrBreachOfTenancyGround.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/SecureOrFlexibleGroundsForPossession.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/SecureOrFlexibleGroundsForPossessionReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/ClaimGroundService.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/ClaimService.java
  src/main/resources/db/migration/V022__add_ground_description.sql
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaimTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/IntroductoryDemotedOrOtherGroundsForPossessionTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/RentArrearsOrBreachOfTenancyGroundTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/SecureOrFlexibleGroundsForPossessionTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/ClaimGroundServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/ClaimServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-620

#650 HDPI-1932-QA-Additional-reasons-for-possession
  src/e2eTest/data/page-data/additionalReasonsForPossession.page.data.ts
  src/e2eTest/data/page-data/claimingCosts.page.data.ts
  src/e2eTest/data/page-data/underlesseeOrMortgageeEntitledToClaim.page.data.ts
  src/e2eTest/playwright.config.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: aat/no-changes, ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-650

#647 HDPI-1932: Add additional reasons for possession page
  src/e2eTest/data/page-data/additionalReasonsForPossession.page.data.ts
  src/e2eTest/data/page-data/claimingCosts.page.data.ts
  src/e2eTest/data/page-data/underlesseeOrMortgageeEntitledToClaim.page.data.ts
  src/e2eTest/playwright.config.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/ShowConditions.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/AdditionalReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/ClaimEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/PcsCaseEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/AdditionalReasonsForPossession.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EntitledToClaimRelief.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/ClaimService.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/PartyService.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseMergeService.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseService.java
  src/main/resources/db/migration/V023__claim_other_reasons.sql
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/ShowConditionsTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaimTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/ClaimServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PartyServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseMergeServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-647

#677 HDPI-1816-QA
  src/e2eTest/data/page-data/applications.page.data.ts
  src/e2eTest/data/page-data/completeYourClaim.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-677

#663 Hdpi 1774 claimant circumstances automation
  src/e2eTest/data/page-data/claimantCircumstances.page.data.ts
  src/e2eTest/data/page-data/claimantName.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/interfaces/action.interface.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-663

#682 HDPI-1874-QA: Completing your claim page
  src/e2eTest/data/page-data/completeYourClaim.page.data.ts
  src/e2eTest/data/page-data/statementOfTruth.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr-values:elasticsearch, pr:runE2eTests, rel:pcs-api-pr-682

#692 Fixed e2e tests that are intermittently failing in the pipelines
  src/e2eTest/playwright.config.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/clickButton.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-692

#688 HDPI-1908-QA-AlternativesToPossession-Suspension
  src/e2eTest/data/page-data/alternativesToPossession.page.data.ts
  src/e2eTest/data/page-data/groundsForPossession.page.data.ts
  src/e2eTest/data/page-data/housingAct.page.data.ts
  src/e2eTest/data/page-data/reasonsForRequestingASuspensionOrder.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/check.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-688

#661 HDPI-2163: update the case number label
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/CCDCaseRepository.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/State.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/CCDCaseRepositoryTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-661

#691 HDPI-1815-QA: Additional file upload Documents
  src/e2eTest/data/inputFiles/tenancy.pdf
  src/e2eTest/data/page-data/uploadAdditionalDocs.page.data.ts
  src/e2eTest/data/page-data/wantToUploadDocuments.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/controller.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-691

#644 HDPI-1719 adding consumer deploy check tag for pact tests
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/pcs/contract/ServiceAuthorisationConsumerTest.java
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-644
