Repository hmcts/pcs-api, pull requests merged in 2025-08, with the labels that each got.

#414 HDPI-1459
  Dockerfile
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-414

#436 Revert "chore(deps): update dependency allure-js-commons to v3.3.3"
  src/e2eTest/yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-436

#428 HDPI-1493
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/e2eTest/package.json
  src/e2eTest/playwright.config.ts
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-428

#448 HDPI-1549 fix pcs-api master
  src/e2eTest/yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-448

#394 HDPI-1271: Add eligibility check for Claimant Type
  build.gradle
  src/cftlibTest/java/uk/gov/hmcts/reform/pcs/TestWithCCD.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/common/PageBuilder.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/ClaimantType.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/EventId.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ClaimantTypeNotEligibleEngland.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ClaimantTypeNotEligibleWales.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelection.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddress.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimantType.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectLegislativeCountry.java
  src/main/java/uk/gov/hmcts/reform/pcs/postcodecourt/exception/EligibilityCheckException.java
  src/main/java/uk/gov/hmcts/reform/pcs/postcodecourt/model/LegislativeCountry.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/BasePageTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelectionTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddressTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimantTypeTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/type/DynamicStringListElementTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/type/DynamicStringListTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/postcodecourt/model/LegislativeCountryTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/testingsupport/endpoint/TestingSupportControllerTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-394

#407 HDPI-1274: Select claim type in ExUI journey
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ClaimTypeNotEligibleEngland.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ClaimTypeNotEligibleWales.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimType.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/domain/VerticalYesNoTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimTypeTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-407

#451 HDPI-1254-Automation-Eligibility Checks for non cross border postcodes-Happy Path
  src/e2eTest/data/page-data/housingPossessionClaim.page.data.ts
  src/e2eTest/data/page-data/legislativeCountry.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-451

#456 HDPI-1355: add new data structures for case creation and enhance radi…
  src/e2eTest/data/page-data/addressDetails.page.data.ts
  src/e2eTest/data/page-data/applicantDetails.page.data.ts
  src/e2eTest/data/page-data/borderPostcode.page.data.ts
  src/e2eTest/data/page-data/checkingNotice.page.data.ts
  src/e2eTest/data/page-data/createCase.page.data.ts
  src/e2eTest/data/page-data/groundsForPossession.page.data.ts
  src/e2eTest/data/page-data/mediationAndSettlement.page.data.ts
  src/e2eTest/data/page-data/preActionProtocol.page.data.ts
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/utils/actions/element-actions/clickRadioButton.action.ts
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-456

#458 HDPI-1274,1275,1276 test automation
  src/e2eTest/data/page-data/claimType.page.data.ts
  src/e2eTest/data/page-data/claimantName.page.data.ts
  src/e2eTest/data/page-data/contactPreferences.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/clickRadioButton.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-458

#480 Setting tomcat embed core & websocket to remove CVE's
  build.gradle
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-480

#474 HDPI-1489-QA: Served Notice page
  src/e2eTest/data/page-data/checkingNotice.page.data.ts
  src/e2eTest/data/page-data/groundsForPossession.page.data.ts
  src/e2eTest/data/page-data/mediationAndSettlement.page.data.ts
  src/e2eTest/data/page-data/noticeDetails.page.data.ts
  src/e2eTest/data/page-data/preActionProtocol.page.data.ts
  src/e2eTest/data/page-data/rentDetails.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/clickRadioButton.action.ts
  src/e2eTest/utils/actions/element-actions/inputText.action.ts
  src/e2eTest/utils/registry/action.registry.ts
  src/e2eTest/utils/validations/element-validations/pageHeader.validation.ts
  src/e2eTest/utils/validations/element-validations/text.validation.ts
Labels: aat/no-changes, ns:pcs, prd:pcs, rel:pcs-api-pr-474

#494 HDPI-1682
  src/contractTest/java/uk/gov/hmcts/reform/pcs/contract/EvidenceManagementConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/pcs/contract/IdamConsumerTest.java
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-494

#504 HDPI-1712: Revert Sonarqube plugin version
  build.gradle
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-504

#486 HDPI-1269: Handle Scotland, NI, Channel Islands & IoM postcodes in PropertyNotEligible flow
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelection.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddress.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/PropertyNotEligible.java
  src/main/java/uk/gov/hmcts/reform/pcs/postcodecourt/model/LegislativeCountry.java
  src/main/resources/db/testdata/V010.2__add_scotland_ni_iom_channel_islands_postcodes.sql
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddressTest.java
Labels: aat/no-changes, ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-486

#485 HDPI-1490: Postcode not assigned to a court
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelection.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddress.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/PostcodeNotAssignedToCourt.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelectionTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddressTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/PostcodeNotAssignedToCourtTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-485
