Repository hmcts/pcs-api, pull requests merged in 2025-09, with the labels that each got.

#499 HDPI-1506: rent details
  .vscode/settings.json
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/CCDCaseRepository.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/RentPaymentFrequency.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/TenancyLicence.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/NoticeDetails.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/RentArrears.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/RentDetails.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseService.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-499

#500 HDPI-1506-QA:Rent details
  src/e2eTest/data/page-data/addressDetails.page.data.ts
  src/e2eTest/data/page-data/dailyRentAmount.page.data.ts
  src/e2eTest/data/page-data/detailsOfrentArrears.page.data.ts
  src/e2eTest/data/page-data/rentDetails.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/inputText.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: aat/no-changes, ns:pcs, prd:pcs, pr-values:ccd, rel:pcs-api-pr-500

#540 Small fix to after always call on fortify-scan
  Jenkinsfile_nightly
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-540

#507 HDPI-1681: Enable definition file upload in master pipeline
  Jenkinsfile_CNP
Labels: aat/no-changes, ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-api-pr-507

#527 Hdpi 1596 update mediation and settlement
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/MediationAndSettlement.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/MediationAndSettlementTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-527

#518 HDPI-1429: Split creation event into two and save unsubmitted answers
  src/cftlibTest/java/uk/gov/hmcts/reform/pcs/TestWithCCD.java
  src/e2eTest/data/page-data/addressDetails.page.data.ts
  src/e2eTest/data/page-data/borderPostcode.page.data.ts
  src/e2eTest/data/page-data/legislativeCountry.page.data.ts
  src/e2eTest/data/page-data/provideMoreDetailsOfClaim.page.data.ts
  src/e2eTest/data/page-data/resumeClaim.page.data.ts
  src/e2eTest/data/page-data/resumeClaimOptions.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/clickButton.action.ts
  src/e2eTest/utils/controller.ts
  src/e2eTest/utils/helpers/idam-helpers/idam.helper.ts
  src/e2eTest/utils/interfaces/validation.interface.ts
  src/e2eTest/utils/registry/action.registry.ts
  src/e2eTest/utils/registry/validation.registry.ts
  src/e2eTest/utils/validations/element-validations/radioButton.validation.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/CCDCaseRepository.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/CaseType.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/ShowConditions.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/State.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/UnsubmittedCaseDataMixIn.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/PcsCaseEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/UnsubmittedCaseDataEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/EventId.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/builder/SavingPageBuilder.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/builder/SavingPageBuilderFactory.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ClaimantInformation.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelection.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddress.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/PropertyNotEligible.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ResumeClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimType.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimantType.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectLegislativeCountry.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/repository/UnsubmittedCaseDataRepository.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseService.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/UnsubmittedCaseDataService.java
  src/main/java/uk/gov/hmcts/reform/pcs/config/JacksonConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pcs/exception/UnsubmittedDataException.java
  src/main/resources/db/migration/V017__case_legislative_country_column.sql
  src/main/resources/db/migration/V018__unsubmitted_data.sql
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/CCDCaseRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaimTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaimTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/builder/SavingPageBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/CrossBorderPostcodeSelectionTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/EnterPropertyAddressTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ResumeClaimTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimTypeTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SelectClaimantTypeTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/UnsubmittedCaseDataServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-518

#542 Enabled e2e tests for PR pipelines
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  build.gradle
  src/e2eTest/package.json
  src/e2eTest/playwright.config.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/tests/searchCase.spec.ts
Labels: dependencies, ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, rel:pcs-api-pr-542

#531 HDPI-1521: QA-Daily rent amount page
  src/e2eTest/data/page-data/dailyRentAmount.page.data.ts
  src/e2eTest/data/page-data/detailsOfRentArrears.page.data.ts
  src/e2eTest/data/page-data/mediationAndSettlement.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/searchCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/inputText.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-531

#536 HDPI-1503 Notice Details screen
  Jenkinsfile_CNP
  src/e2eTest/data/page-data/noticeDetails.page.data.ts
  src/e2eTest/data/page-data/noticeOfYourIntention.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/inputText.action.ts
  src/e2eTest/utils/registry/action.registry.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/NoticeServiceMethod.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/TenancyLicence.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/NoticeDetails.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/NoticeDetailsService.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/TenancyLicenceService.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaimTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/NoticeDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/NoticeDetailsServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-536

#588 E2e test framework improvements
  README.md
  src/e2eTest/playwright.config.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/tests/searchCase.spec.ts
  src/e2eTest/utils/actions/element-actions/clickButton.action.ts
  src/e2eTest/utils/actions/element-actions/clickRadioButton.action.ts
  src/e2eTest/utils/actions/element-actions/clickTab.action.ts
  src/e2eTest/utils/actions/element-actions/inputText.action.ts
  src/e2eTest/utils/actions/element-actions/select.action.ts
  src/e2eTest/utils/controller.ts
  src/e2eTest/utils/interfaces/action.interface.ts
  src/e2eTest/utils/interfaces/validation.interface.ts
  src/e2eTest/utils/validations/element-validations/bannerAlert.validation.ts
  src/e2eTest/utils/validations/element-validations/error-message.validation.ts
  src/e2eTest/utils/validations/element-validations/formLabelValue.validation.ts
  src/e2eTest/utils/validations/element-validations/optionList.validation.ts
  src/e2eTest/utils/validations/element-validations/pageHeader.validation.ts
  src/e2eTest/utils/validations/element-validations/radioButton.validation.ts
  src/e2eTest/utils/validations/element-validations/text.validation.ts
  src/e2eTest/utils/validations/element-validations/visibility.validation.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-588

#576 HDPI-1555-claim-for-money-page-implementation
  src/e2eTest/data/page-data/claimantCircumstances.page.data.ts
  src/e2eTest/data/page-data/moneyJudgment.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/TenancyLicence.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/ClaimantCircumstances.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/MoneyJudgment.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/TenancyLicenceService.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/TenancyLicenceServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-576

#611 HDPI-1681
  Jenkinsfile_CNP
  build.gradle
Labels: ns:pcs, prd:pcs, pr-values:ccd, rel:pcs-api-pr-611

#619 Quick PR to upgrade netty to stop major CVE risks
  build.gradle
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-619

#568 HDPI-1542-QA: Details of rent arrears
  src/e2eTest/data/inputFiles/rentArrears.docx
  src/e2eTest/data/inputFiles/rentArrears.pdf
  src/e2eTest/data/inputFiles/rentArrears.png
  src/e2eTest/data/page-data/detailsOfRentArrears.page.data.ts
  src/e2eTest/data/page-data/moneyJudgement.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/check.action.ts
  src/e2eTest/utils/actions/element-actions/uploadFile.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-568

#612 HDPI-1952
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/inputText.action.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-612

#585 Hdpi 1543 test automation implement assured tenancy possession grounds no rent arrears screens
  src/e2eTest/data/page-data/reasonsForPossession.page.data.ts
  src/e2eTest/data/page-data/whatAreYourGroundsForPossession.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-585

#633 Move swagger publishing to integration test
  .github/workflows/publish-openapi.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/pcs/openapi/OpenAPIPublisherTest.java
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-633

#553 TestAutomation-HDPI-1578-Secure or flexible tenancy
  src/e2eTest/data/page-data/mandatoryAndDiscretionaryGrounds.page.data.ts
  src/e2eTest/data/page-data/reasonsForPossession.page.data.ts
  src/e2eTest/data/page-data/rentArrearsOrBreachOfTenancy.page.data.ts
  src/e2eTest/data/page-data/whatAreYourGroundsForPossession.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/check.action.ts
  src/e2eTest/utils/registry/action.registry.ts
Labels: aat/no-changes, ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-553

#549 HDPI-1578 implement secured/flexible tenancy possession grounds
  src/e2eTest/data/page-data/mandatoryAndDiscretionaryGrounds.page.data.ts
  src/e2eTest/data/page-data/reasonsForPossession.page.data.ts
  src/e2eTest/data/page-data/rentArrearsOrBreachOfTenancy.page.data.ts
  src/e2eTest/data/page-data/whatAreYourGroundsForPossession.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/registry/action.registry.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/RentArrearsOrBreachOfTenancy.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleDiscretionaryGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleDiscretionaryGroundsAlternativeAccomm.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleGroundsReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleMandatoryGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleMandatoryGroundsAlternativeAccomm.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/entity/PcsCaseEntity.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/model/PossessionGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/model/SecureOrFlexibleReasonsForGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/RentArrearsOrBreachOfTenancyGround.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SecureOrFlexibleGroundsForPossession.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/createpossessionclaim/SecureOrFlexibleGroundsForPossessionReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/GroundForPossessionAdditionalGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/GroundForPossessionRentArrears.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/GroundsForPossession.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/ResumeClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/TenancyLicenceDetails.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseService.java
  src/main/resources/db/migration/V019__add_possession_grounds.sql
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/GroundForPossessionRentArrearsTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/RentArrearsOrBreachOfTenancyGroundTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/SecureOrFlexibleGroundsForPossessionTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/TenancyLicenceDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/PcsCaseServiceTest.java
Labels: aat/no-changes, ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-549

#637 FIX- Exclude OpenAPI workflow file from sonar
  build.gradle
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-api-pr-637

#639 Fix - Updating Sonar excluded Open API work flows file path
  build.gradle
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-639

#613 HDPI-1927: Use PCS caseworker-pcs-solicitor role for case creation
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/cftlib/java/uk/gov/hmcts/reform/pcs/CftlibConfig.java
  src/cftlibTest/java/uk/gov/hmcts/reform/pcs/TestWithCCD.java
  src/e2eTest/data/user-data/permanent.user.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/tests/eligibilityCheck.spec.ts
  src/e2eTest/tests/searchCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/custom-actions/login.action.ts
  src/e2eTest/utils/actions/element-actions/clickButton.action.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/accesscontrol/CaseworkerReadAccess.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/accesscontrol/ClaimantAccess.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/accesscontrol/UserRole.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/config/HighLevelDataSetupApp.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/SecureOrFlexibleGroundsReasons.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/State.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/model/NoRentArrearsReasonForGrounds.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CaseworkerUpdateApplication.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/EventId.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ProcessClaimPayment.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-613

#580 HDPI-1546: Map rent statement documents into TenancyLicence JSON
  src/e2eTest/data/inputFiles/NoticeDetails.pdf
  src/e2eTest/data/page-data/moneyJudgement.page.data.ts
  src/e2eTest/playwright.config.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
  src/e2eTest/utils/actions/element-actions/uploadFile.action.ts
  src/e2eTest/utils/registry/validation.registry.ts
  src/e2eTest/utils/validations/element-validations/visibility.validation.ts
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/PCSCase.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/domain/TenancyLicence.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/NoticeDetails.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/RentArrears.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/page/resumepossessionclaim/TenancyLicenceDetails.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/TenancyLicenceService.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/TenancyLicenceServiceTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-580

#590 HDPI-1747: Full postcode validation
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/service/AddressValidator.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/util/PostcodeValidator.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/service/AddressValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/util/PostcodeValidatorTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-590

#645 Change admin approval to QA for e2e tests
  .github/CODEOWNERS
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-645

#651 To avoid dev branches with QA changes being blocked from QA admin approvals
  .github/CODEOWNERS
Labels: ns:pcs, prd:pcs, rel:pcs-api-pr-651

#665 Bump to latest CCD SDK tooling
  build.gradle
  charts/pcs-api/values.ccd.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/CaseType.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CitizenCreateApplication.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CitizenSubmitApplication.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CitizenUpdateApplication.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/CreatePossessionClaim.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ProcessClaimPayment.java
  src/main/java/uk/gov/hmcts/reform/pcs/ccd/event/ResumePossessionClaim.java
  src/test/java/uk/gov/hmcts/reform/pcs/ccd/event/BaseEventTest.java
Labels: ns:pcs, prd:pcs, enable_keep_helm, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-665

#605 HDPI-1657-Introductory-Demoted-and-Other-tenancy-Possession-Grounds
  src/e2eTest/data/page-data/groundsForPossession.page.data.ts
  src/e2eTest/test-README.md
  src/e2eTest/tests/createCase.spec.ts
  src/e2eTest/utils/actions/custom-actions/createCase.action.ts
Labels: ns:pcs, prd:pcs, pr-values:ccd, pr:runE2eTests, rel:pcs-api-pr-605
